[build]
	publish = "client"
	functions = "functions"
	command = "echo 'default context'"

[dev]
	publish = "client"
	functions = "functions"
	functionsPort = 9002

[[redirects]]
	from = "/*"
	to = "/.netlify/functions/api/:splat"
	status = 200